name: Lei Wan
description: Lei Wan's website
menu:
 - page: Papers
   url: /papers
   links:
    - title: Journal papers
      url: "#journal-papers"
    - title: Conference papers
      url: "#conference-papers"
 - page: Research Projects
   url: /research
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
 - page: Teaching
   url: /teaching
 - page: Academic Service
   url: /academic_service
 - page: Contact
   url: /contact
menu_external:
 - title: My Google Scholar Page
   url: "https://scholar.google.com/citations?user=SlvBa5cAAAAJ&hl=en"
 - title: School of Informatics
   url: "https://informatics.xmu.edu.cn/"
 - title: Xiamen University
   url: "https://www.xmu.edu.cn/"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: pires810.github.io/
locale: zh_CN
