name: Lei Wan
description: Lei Wan's website
menu:
 - page: Papers
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Research Projects
   url: /research
   links:
    - title: "Project One"
      url: "#project-one"
    - title: "Project Two"
      url: "#project-two"
    - title: "Project Three"
      url: "#project-three"
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
 - page: Teaching
   url: /teaching
menu_external:
 - title: My Google Scholar Page
   url: "https://scholar.google.com/citations?user=SlvBa5cAAAAJ&hl=en"
 - title: School of Informatics
   url: "https://information.xmu.edu.cn/"
 - title: Xiamen University
   url: "https://www.xmu.edu.cn/"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: pires810.github.io/
locale: zh_CN
